'''自定义异常类'''

class CustomException(Exception):
    pass

class NetworkException(ValueError):
